apiVersion: apps/v1
kind: Deployment
metadata:
  name: thought-khoral-workspace-ui
  namespace: thought-khoral-dev
  labels:
    app.kubernetes.io/name: thought-khoral-workspace-ui
    app.kubernetes.io/part-of: thought-khoral
    thought-khoral.redhat.com/environment: development-only
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thought-khoral-workspace-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thought-khoral-workspace-ui
        app.kubernetes.io/part-of: thought-khoral
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 0
      containers:
        - name: thought-khoral-workspace-ui
          image: localhost/thought-khoral-workspace-ui:dev
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              hostPort: 8082
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: thought-khoral-workspace-ui
  namespace: thought-khoral-dev
  labels:
    app.kubernetes.io/name: thought-khoral-workspace-ui
    app.kubernetes.io/part-of: thought-khoral
spec:
  selector:
    app.kubernetes.io/name: thought-khoral-workspace-ui
  ports:
    - name: http
      port: 8080
      targetPort: http
